"""Body-device semantic protocol shared across Eidolon projects."""

from eidolon_sdk.biz.body.capabilities import (
    BODY_OP_DEVICE_IDENTIFY,
    BODY_OP_DEVICE_ROLL_CALL,
    BODY_OP_DEVICE_REBOOT,
    BODY_OP_DISPLAY_UPDATE,
    BODY_OP_PRESENCE_SET,
    BODY_OP_ROOM_LEAVE,
    BODY_OP_SAFETY_STOP,
    BODY_OP_SOUND_PLAY,
    BODY_OP_VOLUME_SET,
    KNOWN_BODY_CAPABILITIES,
)
from eidolon_sdk.biz.body.models import (
    BodyCapability,
    BodyCommand,
    BodyCommandResult,
    BodyCommandStatus,
    BodyDevice,
    BodyDeviceStatus,
    BodyRiskLevel,
    capability_to_dict,
    command_result_to_dict,
    device_to_dict,
)
from eidolon_sdk.biz.body.manifest import (
    CapabilityDeclaration,
    CapabilityManifest,
    MAX_CAPABILITIES_PER_DEVICE,
    validate_capability_arguments,
)
from eidolon_sdk.biz.body.blackboard import (
    DEVICE_BLACKBOARD_BUCKET,
    DEVICE_BLACKBOARD_SCHEMA_VERSION,
    OwnerDeviceBlackboardSnapshot,
    RuntimeDeviceEntry,
    capability_manifest_revision,
    owner_device_blackboard_key,
)

__all__ = [
    "BODY_OP_DEVICE_IDENTIFY",
    "BODY_OP_DEVICE_ROLL_CALL",
    "BODY_OP_DEVICE_REBOOT",
    "BODY_OP_DISPLAY_UPDATE",
    "BODY_OP_PRESENCE_SET",
    "BODY_OP_ROOM_LEAVE",
    "BODY_OP_SAFETY_STOP",
    "BODY_OP_SOUND_PLAY",
    "BODY_OP_VOLUME_SET",
    "KNOWN_BODY_CAPABILITIES",
    "BodyCapability",
    "BodyCommand",
    "BodyCommandResult",
    "BodyCommandStatus",
    "BodyDevice",
    "BodyDeviceStatus",
    "BodyRiskLevel",
    "DEVICE_BLACKBOARD_BUCKET",
    "DEVICE_BLACKBOARD_SCHEMA_VERSION",
    "CapabilityDeclaration",
    "CapabilityManifest",
    "MAX_CAPABILITIES_PER_DEVICE",
    "OwnerDeviceBlackboardSnapshot",
    "RuntimeDeviceEntry",
    "capability_manifest_revision",
    "owner_device_blackboard_key",
    "validate_capability_arguments",
    "capability_to_dict",
    "command_result_to_dict",
    "device_to_dict",
]
