# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eidolon_agent.v1 import eidolon_pb2 as eidolon__agent_dot_v1_dot_eidolon__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eidolon_agent/v1/eidolon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EidolonAgentStub:
    """The EidolonAgent service is the companion runtime that LiveKit voice agents
    and other authenticated clients invoke instead of a raw LLM. Owner
    authentication, device binding, and token issuance live outside this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/eidolon.agent.v1.EidolonAgent/Chat',
                request_serializer=eidolon__agent_dot_v1_dot_eidolon__pb2.ChatRequest.SerializeToString,
                response_deserializer=eidolon__agent_dot_v1_dot_eidolon__pb2.TurnEvent.FromString,
                _registered_method=True)
        self.PushSignal = channel.unary_unary(
                '/eidolon.agent.v1.EidolonAgent/PushSignal',
                request_serializer=eidolon__agent_dot_v1_dot_eidolon__pb2.SignalRequest.SerializeToString,
                response_deserializer=eidolon__agent_dot_v1_dot_eidolon__pb2.Ack.FromString,
                _registered_method=True)
        self.SubscribeProactive = channel.unary_stream(
                '/eidolon.agent.v1.EidolonAgent/SubscribeProactive',
                request_serializer=eidolon__agent_dot_v1_dot_eidolon__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=eidolon__agent_dot_v1_dot_eidolon__pb2.ProactiveEvent.FromString,
                _registered_method=True)


class EidolonAgentServicer:
    """The EidolonAgent service is the companion runtime that LiveKit voice agents
    and other authenticated clients invoke instead of a raw LLM. Owner
    authentication, device binding, and token issuance live outside this service.
    """

    def Chat(self, request_iterator, context):
        """Primary: bidirectional streaming chat. The client sends ChatRequest
        frames (initial + optional cancels + optional signals); the server emits
        a stream of TurnEvent frames. Both directions stay open for the duration
        of a session (multiple turns share the connection).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushSignal(self, request, context):
        """Push realtime signals (emotion, prosody, vision tags) OUT OF BAND — i.e.
        when no Chat stream is open, or from a producer that isn't driving
        the turn. Requires session_id to route. Prefer the inline
        ChatRequest.signal frame whenever a Chat stream is already open for the
        session: it shares the connection, needs no session_id, and is fused into
        the very next compile pass. Use this unary RPC only for the out-of-band
        case; the two paths converge on the same SignalFuser.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeProactive(self, request, context):
        """Server-stream of proactive utterances the agent decides to initiate.
        Caller subscribes once and decides on its side whether to barge-in.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EidolonAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=eidolon__agent_dot_v1_dot_eidolon__pb2.ChatRequest.FromString,
                    response_serializer=eidolon__agent_dot_v1_dot_eidolon__pb2.TurnEvent.SerializeToString,
            ),
            'PushSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.PushSignal,
                    request_deserializer=eidolon__agent_dot_v1_dot_eidolon__pb2.SignalRequest.FromString,
                    response_serializer=eidolon__agent_dot_v1_dot_eidolon__pb2.Ack.SerializeToString,
            ),
            'SubscribeProactive': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeProactive,
                    request_deserializer=eidolon__agent_dot_v1_dot_eidolon__pb2.SubscribeRequest.FromString,
                    response_serializer=eidolon__agent_dot_v1_dot_eidolon__pb2.ProactiveEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eidolon.agent.v1.EidolonAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eidolon.agent.v1.EidolonAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EidolonAgent:
    """The EidolonAgent service is the companion runtime that LiveKit voice agents
    and other authenticated clients invoke instead of a raw LLM. Owner
    authentication, device binding, and token issuance live outside this service.
    """

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/eidolon.agent.v1.EidolonAgent/Chat',
            eidolon__agent_dot_v1_dot_eidolon__pb2.ChatRequest.SerializeToString,
            eidolon__agent_dot_v1_dot_eidolon__pb2.TurnEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eidolon.agent.v1.EidolonAgent/PushSignal',
            eidolon__agent_dot_v1_dot_eidolon__pb2.SignalRequest.SerializeToString,
            eidolon__agent_dot_v1_dot_eidolon__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeProactive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eidolon.agent.v1.EidolonAgent/SubscribeProactive',
            eidolon__agent_dot_v1_dot_eidolon__pb2.SubscribeRequest.SerializeToString,
            eidolon__agent_dot_v1_dot_eidolon__pb2.ProactiveEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
