"""Device Foundation V1 bindings and host-independent core ports."""

from .authority_locator import (
    AuthorityEndpoint,
    AuthorityLocator,
    AuthorityLocatorError,
    AuthorityLocatorPort,
    LogicalAuthority,
    OwnerDomainDescriptor,
    OwnerDomainTrustAnchor,
    descriptor_key_id,
    sign_descriptor,
    verify_descriptor,
)
from .lifecycle import (
    ActorRef,
    ClaimEventPage,
    ClaimEventRecord,
    DeviceRef,
    OwnerAuthorizationContext,
    RemovalIntent,
    RevokeClaim,
    RevokeClaimResult,
    revoke_claim_fingerprint,
)
from .device_erase import (
    DeviceEraseContractError,
    DeviceLocalEraseAck,
    DeviceLocalEraseCommand,
    DeviceLocalEraseOperationStatus,
    DeviceLocalErasePayload,
    DeviceOperationKeyProof,
    canonical_bytes,
    operation_fingerprint,
    operation_key_id,
    verify_device_erase_ack,
    verify_operation_key_proof,
    verify_p256_signature,
)

__all__ = [
    "AuthorityEndpoint",
    "AuthorityLocator",
    "AuthorityLocatorError",
    "AuthorityLocatorPort",
    "LogicalAuthority",
    "OwnerDomainDescriptor",
    "OwnerDomainTrustAnchor",
    "descriptor_key_id",
    "sign_descriptor",
    "verify_descriptor",
    "ActorRef",
    "ClaimEventPage",
    "ClaimEventRecord",
    "DeviceRef",
    "OwnerAuthorizationContext",
    "RemovalIntent",
    "RevokeClaim",
    "RevokeClaimResult",
    "revoke_claim_fingerprint",
    "DeviceEraseContractError",
    "DeviceLocalEraseAck",
    "DeviceLocalEraseCommand",
    "DeviceLocalEraseOperationStatus",
    "DeviceLocalErasePayload",
    "DeviceOperationKeyProof",
    "canonical_bytes",
    "operation_fingerprint",
    "operation_key_id",
    "verify_device_erase_ack",
    "verify_operation_key_proof",
    "verify_p256_signature",
]
