// Generated by eidolon_sdk.biz.presentation.export. Do not edit.
#pragma once
#include <array>
#include <string_view>
#include <cstdint>
namespace eidolon::presentation {
enum class Output : uint32_t { Speech = 1u << 0, DialogueText = 1u << 1, Expression = 1u << 2, AudioCue = 1u << 3, Motion = 1u << 4 };
inline constexpr std::array<std::string_view, 5> kOutputNames = {"speech", "dialogue_text", "expression", "audio_cue", "motion"};
}
