"""Short-lived owner-scoped device event contracts."""

from .protocol import (
    AMBIENT_PRESENCE_STATE_TYPE,
    COMPANION_FLOW_NODE_TYPE,
    EVENT_DEFAULT_TTL_MS,
    EVENT_MAX_CLOCK_SKEW_MS,
    EVENT_MAX_BYTES,
    EVENT_SCHEMA_VERSION,
    IDENTITY_OWNER_PRESENCE_CONFIRMED_TYPE,
    IDENTITY_OWNER_PRESENCE_CHANGED_TYPE,
    AmbientPresenceState,
    AmbientPresenceStatePayload,
    CompanionFlowNode,
    CompanionFlowNodePayload,
    DeviceEvent,
    EventSource,
    IdentityOwnerPresenceConfirmed,
    IdentityOwnerPresenceChanged,
    OwnerPresenceChangedPayload,
    OwnerPresenceConfirmedPayload,
    normalize_device_event,
    parse_device_event,
)

__all__ = [
    "AMBIENT_PRESENCE_STATE_TYPE",
    "COMPANION_FLOW_NODE_TYPE",
    "EVENT_DEFAULT_TTL_MS",
    "EVENT_MAX_CLOCK_SKEW_MS",
    "EVENT_MAX_BYTES",
    "EVENT_SCHEMA_VERSION",
    "IDENTITY_OWNER_PRESENCE_CONFIRMED_TYPE",
    "IDENTITY_OWNER_PRESENCE_CHANGED_TYPE",
    "AmbientPresenceState",
    "AmbientPresenceStatePayload",
    "CompanionFlowNode",
    "CompanionFlowNodePayload",
    "DeviceEvent",
    "EventSource",
    "IdentityOwnerPresenceConfirmed",
    "IdentityOwnerPresenceChanged",
    "OwnerPresenceChangedPayload",
    "OwnerPresenceConfirmedPayload",
    "normalize_device_event",
    "parse_device_event",
]
