"""Export reviewable schemas, vectors and the embedded catalog from SDK types.

Run ``python -m eidolon_sdk.biz.presentation.export [--check]`` at the SDK root.
"""

from __future__ import annotations
import argparse
import json
from pathlib import Path
from typing import get_args
from . import (
    CancelExpression,
    PlayExpression,
    EXPRESSION_PLAY_OP,
    EXPRESSION_CANCEL_OP,
    FACE_CATALOG,
    FACE_PROFILE,
    MAX_DURATION_MS,
    MAX_PLAN_BYTES,
    MAX_STEPS,
    AssistantResponseCandidate,
    DeviceOutputPolicy,
    ExpressionPlan,
    ExpressionStep,
    Gesture,
    OutputSelection,
    PresentationReceipt,
    ResponseIntent,
    SessionOutputPlan,
)


def artifacts() -> dict[str, str]:
    def dump(value: object) -> str:
        return json.dumps(value, indent=2, ensure_ascii=False) + "\n"

    models = (
        PlayExpression,
        CancelExpression,
        AssistantResponseCandidate,
        DeviceOutputPolicy,
        ExpressionPlan,
        PresentationReceipt,
        ResponseIntent,
        SessionOutputPlan,
    )
    result = {
        f"schemas/{model.__name__}.schema.json": dump(model.model_json_schema()) for model in models
    }
    plan = ExpressionPlan(
        presentation_id="presentation-1",
        response_id="response-1",
        max_duration_ms=1500,
        steps=(
            ExpressionStep(gesture="affirm", variant="subtle", intensity=0.3, duration_ms=1200),
        ),
    )
    result["golden/expression-plan.json"] = dump(plan.model_dump(mode="json"))
    result["golden/silent-session.json"] = dump(
        SessionOutputPlan(
            session_id="session-1",
            policy_revision=1,
            outputs=OutputSelection(expression=True),
            expression_profile=FACE_PROFILE,
        ).model_dump(mode="json")
    )
    actions = [
        {
            "name": name,
            "version": 1,
            "idempotent": True,
            "input_schema": model.model_json_schema(),
            "output_schema": PresentationReceipt.model_json_schema()
            if name == EXPRESSION_PLAY_OP
            else {},
        }
        for name, model in (
            (EXPRESSION_PLAY_OP, PlayExpression),
            (EXPRESSION_CANCEL_OP, CancelExpression),
        )
    ]
    compact_actions = json.dumps(actions, sort_keys=True, separators=(",", ":"))
    manifest = {
        "schema_version": 1,
        "title": "esp-box-3",
        "actions": actions,
        "events": [],
        "media": [{"kind": "audio", "direction": "bidirectional", "codecs": ["opus"]}],
        "properties": [
            {
                "name": name,
                "observable": False,
                "writable": False,
                "schema": {"type": kind, "const": value},
            }
            for name, kind, value in (
                ("interaction_mode", "string", "half_duplex"),
                ("expression.profile", "string", FACE_PROFILE),
                ("output.dialogue_text", "boolean", True),
            )
        ],
    }
    result["golden/companion-manifest.json"] = (
        json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n"
    )
    gestures = get_args(Gesture)
    enum = ", ".join(name.title() for name in gestures)
    names = ", ".join(f'"{name}"' for name in gestures)
    result[
        "embedded/presentation_catalog.h"
    ] = f'''// Generated by eidolon_sdk.biz.presentation.export. Do not edit.
#pragma once
#include <array>
#include <cstdint>
#include <cstddef>
#include <string_view>
namespace eidolon::expression {{
inline constexpr char kManifestActions[] = R"manifest({compact_actions})manifest";
inline constexpr char kPlayOp[] = "{EXPRESSION_PLAY_OP}";
inline constexpr char kCancelOp[] = "{EXPRESSION_CANCEL_OP}";
inline constexpr char kProfile[] = "{FACE_PROFILE}";
inline constexpr char kCatalogRevision[] = "{FACE_CATALOG}";
inline constexpr size_t kMaxPlanBytes = {MAX_PLAN_BYTES};
inline constexpr size_t kMaxSteps = {MAX_STEPS};
inline constexpr uint32_t kMaxDurationMs = {MAX_DURATION_MS};
enum class Gesture : uint8_t {{ {enum} }};
inline constexpr std::array<std::string_view, {len(gestures)}> kGestureNames = {{{names}}};
}}
'''
    names = tuple(OutputSelection.model_fields)
    members = ", ".join(
        f"{name.title().replace('_', '')} = 1u << {index}" for index, name in enumerate(names)
    )
    result["embedded/output_catalog.h"] = (
        "// Generated by eidolon_sdk.biz.presentation.export. Do not edit.\n"
        "#pragma once\n#include <array>\n#include <string_view>\n#include <cstdint>\n"
        "namespace eidolon::presentation {\n"
        f"enum class Output : uint32_t {{ {members} }};\n"
        f"inline constexpr std::array<std::string_view, {len(names)}> kOutputNames = {{"
        + ", ".join(f'"{name}"' for name in names)
        + "};\n}\n"
    )
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path("contracts/presentation/v1"))
    args = parser.parse_args()
    stale = []
    for name, content in artifacts().items():
        path = args.root / name
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Stale presentation contracts: " + ", ".join(stale))


if __name__ == "__main__":
    main()
