"""Storage-independent owner model store protocols."""

from __future__ import annotations

from typing import Protocol

from .models import CompanionRef, DeviceBindingRecord, DeviceRegistryRecord, OwnerRef


class OwnerStore(Protocol):
    async def get(self, owner_id: str) -> OwnerRef | None: ...

    async def list_all(self) -> dict[str, OwnerRef]: ...


class CompanionStore(Protocol):
    async def get(self, companion_id: str) -> CompanionRef | None: ...

    async def list_for_owner(self, owner_id: str) -> list[CompanionRef]: ...


class DeviceStore(Protocol):
    async def get(self, device_id: str) -> DeviceRegistryRecord | None: ...

    async def put(self, record: DeviceRegistryRecord) -> None: ...

    async def delete(self, device_id: str) -> None: ...

    async def list_all(self) -> dict[str, DeviceRegistryRecord]: ...


class DeviceBindingStore(Protocol):
    async def get(self, device_id: str) -> DeviceBindingRecord | None: ...

    async def bind(self, record: DeviceBindingRecord) -> None: ...

    async def unbind(self, device_id: str) -> None: ...

    async def list_for_owner(self, owner_id: str) -> dict[str, DeviceBindingRecord]: ...
