"""Storage-independent registry store protocols."""

from __future__ import annotations

from typing import Protocol

from .models import TenantSpec, UserRegistryRecord


class TenantStore(Protocol):
    async def get(self, tenant_id: str) -> TenantSpec | None: ...

    async def put(self, spec: TenantSpec) -> None: ...

    async def delete(self, tenant_id: str) -> None: ...

    async def list_all(self) -> list[TenantSpec]: ...

    async def count(self) -> int: ...


class UserStore(Protocol):
    async def get(self, user_id: str) -> UserRegistryRecord | None: ...

    async def put(self, record: UserRegistryRecord) -> None: ...

    async def delete(self, user_id: str) -> None: ...

    async def list_all(self) -> dict[str, UserRegistryRecord]: ...

    async def allocate_memory_port(self) -> int: ...

